global class ExternalMediaAddressInputRepresentation {
	global String addressLine1;
	global String addressLine2;
	global String addressLine3;
	global String alternatePhone;
	global String city;
	global String country;
	global String email;
	global String phone;
	global String state;
	global String zipcode;
	global ExternalMediaAddressInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}